
package model;

/**
 *
 * @author senma
 */
public class Card implements Comparable<Card>{
    private int value;
    private CardState state;
    private CardType type;
    
    /**
     * Creates a Hidden card with a final int value (generated by Logic). 
     * Type is meant to be dictated by the user
     * 
     * @param value
     * @param type
     */
    
    public Card(int value, CardType type) {
        this.state=CardState.HIDDEN;
        this.value=value;
        this.type=type;
    }
    
    public void ChangeStateToHidden(){
        this.state=CardState.HIDDEN;
    }
    
    public void ChangeStateToRevealed(){
        this.state=CardState.REVEALED;
    }
    
    public void ChangeStateToMatched(){
        this.state=CardState.MATCHED;
    }
    
    public int getValue(){
        return value;
    }
    
    public CardState getState(){
        return state;
    }
    
     @Override
    public String toString(){
        String info= "Value: " +this.value+ " Status: " +this.state;
        return info;
    }

    @Override
    public int compareTo(Card o) {
        return this.value-o.value;
    }
}
